In [1]:
import numpy as np

## Arrays

Let's create a small array:

In [2]:
a = [1, 4, 9, 16]
a

[1, 4, 9, 16]

Indexing and assignments in Python:

In [28]:
a[0] = 10
a[1:3] = [20, 30]
a

[10, 20, 30, 16]

### Element Type
Since we used only integers when creating the array, Julia inferred that the array is only meant to hold integers (NumPy arrays behave the same way). Let's try adding a string:

In [29]:
try:
  a[2] = "Three" #string 
except ex:
  ex
a

[10, 20, 'Three', 16]

An empty array is automatically an `Any` array:

In [31]:
a = []
a

[]

You can use NumPy arrays' `dtype` function to get an array's element type:

In [49]:
a = np.array([1, 4, 9, 16])
a.dtype

dtype('int32')

In [53]:
a = np.array([1, 2, 3.0, 4.0])
print(a)
a.dtype

[1. 2. 3. 4.]


dtype('float64')

A mix of unrelated types results in an `Any` array:

In [ ]:
[1, 2, "Three", 4]

## Append, Extend and Pop 

In [57]:
a = [1]
a.append(4)
a.extend([9, 16])
a

[1, 4, 9, 16]

In [58]:
a

[1, 4, 9, 16]

In [59]:
a.pop()

16

There are many more functions you can call on an array. We will see later how to find them.

## Multidimensional Arrays
Importantly, Python arrays can be multidimensional:

In [67]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can index them:

In [71]:
M[1:, 2:]

array([[ 7,  8],
       [11, 12]])

You can transpose a matrix using the `.T`:

In [73]:
M.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Arrays can be concatenated vertically using the `np.r_` function:

In [77]:
M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])
np.r_[M1, M2]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
np.c_[M1, M2]

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

You can combine horizontal and vertical concatenation:

In [84]:
M3 = np.array([9, 10, 11, 12])
M3

array([ 9, 10, 11, 12])

In [ ]:
np.r_[np.c_[M1, M2], M3]

The `print()` function:

In [101]:
print("Vector: ", [1, 2, 3, 4])
print("Column vector: ", np.array([[1], [2], [3], [4]]))
print("Row vector: ", np.array([1, 2, 3, 4]))
print("Matrix: ", np.array([[1, 2, 3], [4, 5, 6]]))

Vector:  [1, 2, 3, 4]
Column vector:  [[1]
 [2]
 [3]
 [4]]
Row vector:  [1 2 3 4]
Matrix:  [[1 2 3]
 [4 5 6]]


|Julia|Python
|-----|------
|`a = [1, 2, 3]` | `a = [1, 2, 3]`<br />or<br />`import numpy as np`<br />`np.array([1, 2, 3])`
|`a[1]` | `a[0]`
|`a[end]` | `a[-1]`
|`a[2:end-1]` | `a[1:-1]`
|`push!(a, 5)` | `a.append(5)`
|`pop!(a)` | `a.pop()`
|`M = [1 2 3]` | `np.array([[1, 2, 3]])`
|`M = [1 2 3]'` | `np.array([[1, 2, 3]]).T`
|`M = hvcat(1,  1, 2, 3)` | `np.array([[1], [2], [3]])`
|`M = [1 2 3`<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;`4 5 6]`<br />or<br />`M = [1 2 3; 4 5 6]` | `M = np.array([[1,2,3], [4,5,6]])`
|`M[1:2, 2:3]` | `M[0:2, 1:3]`
|`[M1; M2]` | `np.r_[M1, M2]`
|`[M1  M2]` | `np.c_[M1, M2]`
|`[M1 M2; M3]` | `np.r_[np.c_[M1, M2], M3]`


## Comprehensions
List comprehensions are available in Python:

In [114]:
a = [x**2 for x in range(1, 5)]
a

[1, 4, 9, 16]

You can filter elements using an `if` clause:

In [121]:
a = [x**2 for x in range(1, 6) if x not in (2, 4)]
a

[1, 9, 25]

Comprehensions can contain nested loops:

In [106]:
a = [(i, j) for i in range(1, 4) for j in range(1, i+1)]
a

[(1, 1), (2, 1), (2, 2), (3, 1), (3, 2), (3, 3)]

## Conditional sub-Arrays
You can select all the parameters in an array which satisfy a condition and put them into another array. 

In [137]:
a = np.array([-4, -3, -2, -1, 0, 1, 2, 3, 4])
b = a[a > 0]
b = b[b < 3]
b

array([1, 2])

# Dictionaries

In [1]:
d = {"call": "long", "put": "short"}
print(d["call"])

long


In [3]:
d.get("neutral", "pardon?")

'pardon?'

In [4]:
d.keys()

dict_keys(['call', 'put'])

In [5]:
d.values()

dict_values(['long', 'short'])

In [10]:
"long" in d
# "long" in d.keys()

False

Dict comprehensions work as you would expect:

In [11]:
d = {i: i**2 for i in range(1, 6)}
d

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [12]:
for k, v in d.items():
    print(f"{k} maps to {v}")

1 maps to 1
2 maps to 4
3 maps to 9
4 maps to 16
5 maps to 25


And you can merge dictionaries like this:

In [13]:
d1 = {"tree": "arbre", "love": "amour", "coffee": "café"}
d2 = {"car": "voiture", "love": "aimer"}
d = {**d1, **d2}
d

{'tree': 'arbre', 'love': 'aimer', 'coffee': 'café', 'car': 'voiture'}

Or if you want to update the first dictionary instead of creating a new one:

In [15]:
d1.update(d2)
d1

{'tree': 'arbre', 'love': 'aimer', 'coffee': 'café', 'car': 'voiture'}

In [18]:
a = [1, 2, 3]
d = {a : "My array"}

TypeError: unhashable type: 'list'

|Julia|Python
|-----|------
|`Dict("tree"=>"arbre", "love"=>"amour")` | `{"tree": "arbre", "love": "amour"}`
|`d["arbre"]` | `d["arbre"]`
|`get(d, "unknown", "default")` | `d.get("unknown", "default")`
|`keys(d)` | `d.keys()`
|`values(d)` | `d.values()`
|`haskey(d, k)` | `k in d`
|`Dict(i=>i^2 for i in 1:4)` | `{i: i**2 for i in 1:4}`
|`for (k, v) in d` | `for k, v in d.items():`
|`merge(d1, d2)` | `{**d1, **d2}`
|`merge!(d1, d2)` | `d1.update(d2)`

# Sets

Let's create a couple sets:

In [19]:
odds = {1, 3, 5, 7, 9, 11}
primes = {2, 3, 5, 7, 11}
primes

{2, 3, 5, 7, 11}

The order of sets is not guaranteed.

In [20]:
5 in primes

True

Now let's get the union of these two sets:

In [21]:
odds | primes # union

{1, 2, 3, 5, 7, 9, 11}

In [22]:
odds.union(primes)

{1, 2, 3, 5, 7, 9, 11}

In [23]:
odds & primes # intersection

{3, 5, 7, 11}

Or use the `intersect()` function:

In [24]:
odds.intersection(primes)

{3, 5, 7, 11}

Next, let's get the [set difference](https://en.wikipedia.org/wiki/Complement_(set_theory)#Relative_complement) and the [symetric difference](https://en.wikipedia.org/wiki/Symmetric_difference) between these two sets:

In [25]:
odds - primes # set difference

{1, 9}

In [26]:
odds.difference(primes)

{1, 9}

In [27]:
odds ^ primes # symmetric difference

{1, 2, 9}

In [28]:
odds.symmetric_difference(primes)

{1, 2, 9}

Lastly, set comprehensions work just fine:

In [29]:
{i**2 for i in range(1, 5)}

{1, 4, 9, 16}

|Julia|Python
|-----|------
|`Set([1, 3, 5, 7])` | `{1, 3, 5, 7}`
|`5 in odd` | `5 in odd`
|`Set([i^2 for i in 1:4])` | `{i**2 for i in range(1, 5)}`
|`odd ∪ primes` | `odd | primes`
|`union(odd, primes)` | `odd.union(primes)`
|`odd ∩ primes` | `odd & primes`
|`insersect(odd, primes)` | `odd.intersection(primes)`
|`setdiff(odd, primes)` | `odd - primes` or `odd.difference(primes)`
|`symdiff(odd, primes)` | `odd ^ primes` or `odd.symmetric_difference(primes)`

# Tuples

In [31]:
t = (1729, "string", 100.0)
t

(1729, 'string', 100.0)

Let's look at one element:

In [32]:
t[0]

1729

In [33]:
t[0:2]

(1729, 'string')

In [34]:
t[-1]

100.0

In [36]:
t[-2:]

('string', 100.0)

In Python, tuples are immutable:

In [39]:
try:
  t[2] = 2
except:
  print("error!")

error!


In [41]:
empty_tuple = ()
one_element_tuple = (42,)
one_element_tuple

(42,)

You can unpack a tuple in Python:

In [47]:
a, b, c, d, e = (1729, "string", 100.0, 3.14, "euler")
print(f"a={a}, b={b}, c={c}, d={d}, e={e}")

a=1729, b=string, c=100.0, d=3.14, e=euler


It also works with nested tuples, just like in Python:

In [48]:
(a, (b, c), (d, e)) = (1, ("Two", 3), (4, 5))
print(f"a={a}, b={b}, c={c}, d={d}, e={e}")

a=1, b=Two, c=3, d=4, e=5


However, consider this example:

In [49]:
a, b, c = (1, "Two", 3, 4, 5)
print(f"a={a}, b={b}, c={c}")

ValueError: too many values to unpack (expected 3)

In [51]:
t = (1, "Two", 3, 4, 5)
a, b, *c = t
print(f"a={a}, b={b}, c={c}")

a=1, b=Two, c=[3, 4, 5]


## Named Tuples

In [54]:
from collections import namedtuple

In [56]:
Rating = namedtuple("Rating", ["name", "category", "stars"])
nt = Rating(name="Julia", category="Language", stars=5)
nt

Rating(name='Julia', category='Language', stars=5)

In [57]:
nt.name

'Julia'

In [58]:
print(nt)

Rating(name='Julia', category='Language', stars=5)


# Class

In [1]:
class Option:
 
    # A simple class
    # attribute
    def __init__(self, iscall, strike_price, maturity):
        self.iscall = iscall
        self.strike_price = strike_price
        self.maturity = maturity


In [5]:
p = Option(True, 100.0, 1.0)

In [6]:
p.maturity

1.0

In [8]:
class Option:
 
    # A simple class
    # attribute
    iscall = True
    def __init__(self, strike_price, maturity):
        self.strike_price = strike_price
        self.maturity = maturity


In [10]:
Option(100., 1.)

In [11]:
class Option:
 
    # A simple class
    # attribute
    iscall = True
    def __init__(self, strike_price, maturity):
        self.strike_price = strike_price
        self.maturity = maturity
    def getMaturity(self):
        return self.maturity


In [13]:
p = Option(100., 1.)
p.getMaturity()

1.0

# Enums

In [14]:
from enum import Enum
class Fruit(Enum):
    APPLE = 1
    BANANA = 2
    ORANGE = 3
Fruit

<enum 'Fruit'>

In [15]:
Fruit(2)

<Fruit.BANANA: 2>

Or you can get a `Fruit` instance using the value:

In [16]:
Fruit(2)

<Fruit.BANANA: 2>

And you can get all the instances of the enum easily:

In [17]:
dir(Fruit)

['APPLE',
 'BANANA',
 'ORANGE',
 '__class__',
 '__doc__',
 '__members__',
 '__module__']

# Object Identity

In [68]:
id(Fruit(2))

1399507950848

In [73]:
id(Fruit(2))

1399507950848

In [75]:
a = [1, 2, 4]
b = [1, 2, 4]
a == b

True

In [76]:
a is b

False