# Julia's Hiearchical and Fundamental Type System

Julia defines and provides functions for standard data types such as

*   strings
*   integers
*   floats
*   arrays and matrices
*   etc...

The basic process in Julia is the REPL, which stands for "Read-Evaluate-Print Loop".

Every time you take a step in Julia (hitting Shift-Enter in JuliaBox, for instance), you run through this loop.

Julia's fundamental process is the REPL(Read-Evaluate-Print Loop). This loop is executed each time you take a step in Julia (for example, by pressing Shift-Enter in Visual Studio Code or Google Colab).

## Arrays

Let's create a small array:

In [92]:
a = [1, 4, 9, 16]

4-element Vector{Int64}:
  1
  4
  9
 16

Indexing and assignments work as you would expect:

In [93]:
a[1] = 10
a[2:3] = [20, 30]
a

4-element Vector{Int64}:
 10
 20
 30
 16

### Element Type
Since we used only integers when creating the array, Julia inferred that the array is only meant to hold integers (NumPy arrays behave the same way). Let's try adding a string:

In [94]:
try
  a[3] = "Three" #string 
catch ex
  ex
end

MethodError(convert, (Int64, "Three"), 0x0000000000007b20)

Nope! We get a `MethodError` exception, telling us that Julia could not convert the string `"Three"` to a 64-bit integer (we will discuss exceptions later). If we want an array that can hold any type, like Python's lists can, we must prefix the array with `Any`, which is Julia's root type (like `object` in Python):

In [95]:
a = Any[1, 4, 9, 16]
a[3] = "Three"
a

4-element Vector{Any}:
  1
  4
   "Three"
 16

Prefixing with `Float64`, or `String` or any other type works as well:

In [96]:
b = Float64[1, 4, 9, 16]

4-element Vector{Float64}:
  1.0
  4.0
  9.0
 16.0

An empty array is automatically an `Any` array:

In [ ]:
a = []

You can use the `eltype()` function to get an array's element type (the equivalent of NumPy arrays' `dtype`):

In [ ]:
eltype([1, 4, 9, 16])

If you create an array containing objects of different types, Julia will do its best to use a type that can hold all the values as precisely as possible. For example, a mix of integers and floats results in a float array:

In [ ]:
[1, 2, 3.0, 4.0]

A mix of unrelated types results in an `Any` array:

In [ ]:
[1, 2, "Three", 4]

If you want to live in a world without type constraints, you can prefix all you arrays with `Any`, and you will feel like you're coding in Python. But I don't recommend it: the compiler can perform a bunch of optimizations when it knows exactly the type and size of the data the program will handle, so it will run much faster. So when you create an empty array but you know the type of the values it will contain, you might as well prefix it with that type (you don't have to, but it will speed up your program).

## Push and Pop
To append elements to an array, use the `push!()` function. By convention, functions whose name ends with a bang `!` may modify their arguments:

In [97]:
a = [1]
push!(a, 4) # similar to plot!(p, x, y)
push!(a, 9, 16)

4-element Vector{Int64}:
  1
  4
  9
 16

And `pop!()` works like in Python:

In [98]:
a

4-element Vector{Int64}:
  1
  4
  9
 16

In [99]:
pop!(a)

16

Equivalent to:

```python
# PYTHON
a.pop()
```

There are many more functions you can call on an array. We will see later how to find them.

## Multidimensional Arrays
Importantly, Julia arrays can be multidimensional, just like NumPy arrays:

In [100]:
M = [1   2   3   4
     5   6   7   8
     9  10  11  12]

3×4 Matrix{Int64}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

Another syntax for this is:

In [ ]:
M = [1 2 3 4; 5 6 7 8; 9 10 11 12]

You can index them much like NumPy arrays:

In [ ]:
M[2:3, 3:4]

You can transpose a matrix using the "adjoint" operator `'`:

In [ ]:
M'
# transpose(M)

As you can see, Julia arrays are closer to NumPy arrays than to Python lists.


Arrays can be concatenated vertically using the `vcat()` function:

In [101]:
M1 = [1 2
      3 4]
M2 = [5 6
      7 8]
vcat(M1, M2)

4×2 Matrix{Int64}:
 1  2
 3  4
 5  6
 7  8

Alternatively, you can use the `[M1; M2]` syntax:

In [102]:
[M1; M2]

4×2 Matrix{Int64}:
 1  2
 3  4
 5  6
 7  8

To concatenate arrays horizontally, use `hcat()`:

In [103]:
hcat(M1, M2)

2×4 Matrix{Int64}:
 1  2  5  6
 3  4  7  8

Or you can use the `[M1 M2]` syntax:

In [ ]:
[M1 M2]

You can combine horizontal and vertical concatenation:

In [ ]:
M3 = [9 10 11 12]
[M1 M2; M3]

Equivalently, you can call the `hvcat()` function. The first argument specifies the number of arguments to concatenate in each block row:

In [ ]:
hvcat((2, 1), M1, M2, M3)

`hvcat()` is useful to create a single cell matrix:

In [ ]:
hvcat(1, 42)

 Or a column vector (i.e., an _n_×1 matrix = a matrix with a single column):

In [ ]:
# hvcat((1, 1, 1), 10, 11, 12) # a column vector with values 10, 11, 12
hvcat(1, 10, 11, 12) # equivalent to the previous line

Alternatively, you can transpose a row vector (but `hvcat()` is a bit faster):

In [ ]:
[10 11 12]'

The REPL and IJulia call `display()` to print the result of the last expression in a cell (except when it is `nothing`). It is fairly verbose:

In [ ]:
display([1, 2, 3, 4])

The `println()` function is more concise, but be careful not to confuse vectors, column vectors and row vectors (printed with commas, semi-colons and spaces, respectively):

In [ ]:
println("Vector: ", [1, 2, 3, 4])
println("Column vector: ", hvcat(1, 1, 2, 3, 4))
println("Row vector: ", [1 2 3 4])
println("Matrix: ", [1 2 3; 4 5 6])

Although column vectors are printed as `[1; 2; 3; 4]`, evaluating `[1; 2; 3; 4]` will give you a regular vector. That's because `[x;y]` concatenates `x` and `y` vertically, and if `x` and `y` are scalars or vectors, you just get a regular vector.

|Julia|Python
|-----|------
|`a = [1, 2, 3]` | `a = [1, 2, 3]`<br />or<br />`import numpy as np`<br />`np.array([1, 2, 3])`
|`a[1]` | `a[0]`
|`a[end]` | `a[-1]`
|`a[2:end-1]` | `a[1:-1]`
|`push!(a, 5)` | `a.append(5)`
|`pop!(a)` | `a.pop()`
|`M = [1 2 3]` | `np.array([[1, 2, 3]])`
|`M = [1 2 3]'` | `np.array([[1, 2, 3]]).T`
|`M = hvcat(1,  1, 2, 3)` | `np.array([[1], [2], [3]])`
|`M = [1 2 3`<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;`4 5 6]`<br />or<br />`M = [1 2 3; 4 5 6]` | `M = np.array([[1,2,3], [4,5,6]])`
|`M[1:2, 2:3]` | `M[0:2, 1:3]`
|`[M1; M2]` | `np.r_[M1, M2]`
|`[M1  M2]` | `np.c_[M1, M2]`
|`[M1 M2; M3]` | `np.r_[np.c_[M1, M2], M3]`


## Comprehensions
List comprehensions are available in Julia, just like in Python (they're usually just called "comprehensions" in Julia):

In [104]:
a = [x^2 for x ∈ 1:4]

4-element Vector{Int64}:
  1
  4
  9
 16

You can filter elements using an `if` clause, just like in Python:

In [105]:
a = [x^2 for x ∈ 1:5 if x ∉ (2, 4)]

3-element Vector{Int64}:
  1
  9
 25

* `a ∉ b` is equivalent to `!(a in b)` (or `a not in b` in Python). You can type `∉` with `\notin<tab>`
* `a ∈ b` is equivalent to `a in b`. You can type it with `\in<tab>`

In Julia, comprehensions can contain nested loops, just like in Python:

In [106]:
a = [(i,j) for i in 1:3 for j in 1:i]

6-element Vector{Tuple{Int64, Int64}}:
 (1, 1)
 (2, 1)
 (2, 2)
 (3, 1)
 (3, 2)
 (3, 3)

Julia comprehensions can also create multi-dimensional arrays (note the different syntax: there is only one `for`):

In [107]:
a = [row * col for row in 1:3, col in 1:5]

3×5 Matrix{Int64}:
 1  2  3   4   5
 2  4  6   8  10
 3  6  9  12  15

## Conditional sub-Arrays
You can select all the parameters in an array which satisfy a condition and put them into another array. 

In [108]:
a = [-4, -3, -2, -1, 0, 1, 2, 3, 4]
b = a[a .> 0]
b = b[b .< 3]

2-element Vector{Int64}:
 1
 2

# Dictionaries
The syntax for dictionaries is a bit different than Python:

In [109]:
d = Dict("call"=>"long", "put"=>"short") #big short
println(d["call"])

long


In [ ]:
println(get(d, "neutral", "pardon?"))

In [ ]:
keys(d)

In [ ]:
values(d)

In [ ]:
haskey(d, "option")

In [ ]:
"love" ∈ keys(d) # this is slower than haskey()

Dict comprehensions work as you would expect:

In [ ]:
d = Dict(i=>i^2 for i in 1:5)

Note that the items (aka "pairs" in Julia) are shuffled, since dictionaries are hash-based, like in Python (although Python sorts them by key for display).

You can easily iterate through the dictionary's pairs like this:

In [ ]:
for (k, v) in d
    println("$k maps to $v")
end

And you can merge dictionaries like this:

In [ ]:
d1 = Dict("tree"=>"arbre", "love"=>"amour", "coffee"=>"café")
d2 = Dict("car"=>"voiture", "love"=>"aimer")

d = merge(d1, d2)

Notice that the second dictionary has priority in case of conflict (it's `"love" => "aimer"`, not `"love" => "amour"`).

Or if you want to update the first dictionary instead of creating a new one:

In [ ]:
merge!(d1, d2) 

In Julia, each pair is an actual `Pair` object:

In [ ]:
p = "tree" => "arbre"
println(typeof(p))
k, v = p
println("$k maps to $v")

Note that any object for which a `hash()` method is implemented can be used as a key in a dictionary. This includes all the basic types like integers, floats, as well as string, tuples, etc. But it also includes arrays! In Julia, you have the freedom to use arrays as keys (unlike in Python), but make sure not to mutate these arrays after insertion, or else things will break! Indeed, the pairs will be stored in memory in a location that depends on the hash of the key at insertion time, so if that key changes afterwards, you won't be able to find the pair anymore:

In [ ]:
a = [1, 2, 3]
d = Dict(a => "My array")
println("The dictionary is: $d")
println("Indexing works fine as long as the array is unchanged: ", d[a])
a[1] = 10
println("This is the dictionary now: $d")
try
    println("Key changed, indexing is now broken: ", d[a])
catch ex
    ex
end

However, it's still possible to iterate through the keys, the values or the pairs:

In [ ]:
for pair in d
    println(pair)
end

|Julia|Python
|-----|------
|`Dict("tree"=>"arbre", "love"=>"amour")` | `{"tree": "arbre", "love": "amour"}`
|`d["arbre"]` | `d["arbre"]`
|`get(d, "unknown", "default")` | `d.get("unknown", "default")`
|`keys(d)` | `d.keys()`
|`values(d)` | `d.values()`
|`haskey(d, k)` | `k in d`
|`Dict(i=>i^2 for i in 1:4)` | `{i: i**2 for i in 1:4}`
|`for (k, v) in d` | `for k, v in d.items():`
|`merge(d1, d2)` | `{**d1, **d2}`
|`merge!(d1, d2)` | `d1.update(d2)`

# Sets

Let's create a couple sets:

In [110]:
odd = Set([1, 3, 5, 7, 9, 11])
prime = Set([2, 3, 5, 7, 11])

Set{Int64} with 5 elements:
  5
  7
  2
  11
  3

The order of sets is not guaranteed, just like in Python.

Use `in` or `∈` (type `\in<tab>`) to check whether a set contains a given value:

In [111]:
5 ∈ odd

true

In [112]:
5 in odd

true

Both of these expressions are equivalent to:

In [ ]:
in(5, odd)

Now let's get the union of these two sets:

In [113]:
odd ∪ prime

Set{Int64} with 7 elements:
  5
  7
  1
  11
  2
  9
  3

∪ is the union symbol, not a U. To type this character, type `\cup<tab>` (it has the shape of a cup). Alternatively, you can just use the `union()` function:

In [ ]:
union(odd, prime)

Now let's get the intersection using the ∩ symbol (type `\cap<tab>`):

In [ ]:
odd ∩ prime

Or use the `intersect()` function:

In [ ]:
my_set = Set([1729])

In [ ]:
intersect(my_set, prime)

Next, let's get the [set difference](https://en.wikipedia.org/wiki/Complement_(set_theory)#Relative_complement) and the [symetric difference](https://en.wikipedia.org/wiki/Symmetric_difference) between these two sets:

In [ ]:
setdiff(odd, prime) # values in odd but not in prime

In [ ]:
symdiff(odd, prime) # values that are not in the intersection

Lastly, set comprehensions work just fine:

In [ ]:
Set([i^2 for i in 1:4])

Note that you can store any hashable object in a `Set` (i.e., any instance of a type for which the `hash()` method is implemented). This includes arrays, unlike in Python. Just like for dictionary keys, you can add arrays to sets, but make sure not to mutate them after insertion.

|Julia|Python
|-----|------
|`Set([1, 3, 5, 7])` | `{1, 3, 5, 7}`
|`5 in odd` | `5 in odd`
|`Set([i^2 for i in 1:4])` | `{i**2 for i in range(1, 5)}`
|`odd ∪ primes` | `odd | primes`
|`union(odd, primes)` | `odd.union(primes)`
|`odd ∩ primes` | `odd & primes`
|`insersect(odd, primes)` | `odd.intersection(primes)`
|`setdiff(odd, primes)` | `odd - primes` or `odd.difference(primes)`
|`symdiff(odd, primes)` | `odd ^ primes` or `odd.symmetric_difference(primes)`

# Tuples

 Julia has tuples, very much like Python. They can contain anything:

In [ ]:
t = (1729, "string", 100.0)

Let's look at one element:

In [ ]:
t[1]

Hey! Did you see that? **Julia is 1-indexed**, like Matlab and other math-oriented programming languages, not 0-indexed like Python and most programming languages. I found it easy to get used to, and in fact I quite like it, but your mileage may vary.

Moreover, the indexing bounds are inclusive. In Python, to get the 1st and 2nd elements of a list or tuple, you would write `t[0:2]` (or just `t[:2]`), while in Julia you write `t[1:2]`.


In [ ]:
t[1:2]

Note that `end` represents the index of the last element in the tuple. So you must write `t[end]` instead of `t[-1]`. Similarly, you must write `t[end - 1]`, not `t[-2]`, and so on.

In [ ]:
t[end]

In [ ]:
t[end - 1:end]

Like in Python, tuples are immutable:

In [ ]:
try
  t[2] = 2
catch ex
  ex
end

The syntax for empty and 1-element tuples is the same as in Python:

In [ ]:
empty_tuple = ()
one_element_tuple = (42,)

You can unpack a tuple, just like in Python (it's called "destructuring" in Julia):

In [ ]:
a, b, c, d, e = (1729, "string", 100.0, pi, "euler")
println("a=$a, b=$b, c=$c, d=$d, e=$e")

It also works with nested tuples, just like in Python:

In [ ]:
(a, (b, c), (d, e)) = (1, ("Two", 3), (4, 5))
println("a=$a, b=$b, c=$c, d=$d, e=$e")

However, consider this example:

In [ ]:
a, b, c = (1, "Two", 3, 4, 5)
println("a=$a, b=$b, c=$c")

In Python, this would cause a `ValueError: too many values to unpack`. In Julia, the extra values in the tuple are just ignored.

If you want to capture the extra values in the variable `c`, you need to do so explicitly:

In [ ]:
t = (1, "Two", 3, 4, 5)
a, b = t[1:2]
c = t[3:end]
println("a=$a, b=$b, c=$c")

Or more concisely:

In [69]:
(a, b), c = t[1:2], t[3:end]
println("a=$a, b=$b, c=$c")

## Named Tuples

Julia supports named tuples:

In [ ]:
nt = (name="Julia", category="Language", stars=5)

In [ ]:
nt.name

In [ ]:
dump(nt)

# Structs
Julia supports structs, which hold multiple named fields, a bit like named tuples:

In [114]:
struct Option # only contains data but not action/behavior (method)
    iscall #data: either true or false
    strike_price #data: price for execution
    maturity # date of execution
end

Structs have a default constructor, which expects all the field values, in order:

In [115]:
p = Option(false, 100.0, 1.0)

Option(false, 100.0, 1.0)

In [116]:
p.maturity

1.0

You can create other constructors by creating functions with the same name as the struct:

In [ ]:
function Option(iscall)
    Option(iscall, 100, 1)
end

function Option()
    Option(true)
end

p = Option()

This creates two constructors: the second calls the first, which calls the default constructor. Notice that you can create multiple functions with the same name but different arguments. We will discuss this later.

These two constructors are called "outer constructors", since they are defined outside of the definition of the struct. You can also define "inner constructors":

In [ ]:
struct Option2
    name
    age
    function Option2(name)
        new(name, -1)
    end
end

function Option2()
    Option2("European")
end

p2 = Option2()

This time, the outer constructor calls the inner constructor, which calls the `new()` function. This `new()` function only works in inner constructors, and of course it creates an instance of the struct.

When you define inner constructors, they replace the default constructor: 

In [ ]:
try
    Option2("Bob", 35)
catch ex
    ex
end

Structs usually have very few inner constructors (often just one), which do the heavy duty work, and the checks. Then they may have multiple outer constructors which are mostly there for convenience.

By default, structs are immutable:

In [ ]:
p.iscall

In [ ]:
try
    p.iscall = false
catch ex
    ex
end

However, it is possible to define a mutable struct:

In [ ]:
mutable struct Option3
    name
    age
end

p3 = Option3("Lucy", 79)
p3.age += 1
p3

Structs look a lot like Python classes, with instance variables and constructors, but where are the methods? We will discuss this later, in the "Methods" section.

# Enums

To create an enum, use the `@enum` macro:

In [ ]:
@enum Fruit apple=1 banana=2 orange=3
Fruit

This creates the `Fruit` enum, with 3 possible values. It also binds the names to the values:

In [ ]:
banana

Or you can get a `Fruit` instance using the value:

In [ ]:
Fruit(2)

And you can get all the instances of the enum easily:

In [ ]:
instances(Fruit)

# Object Identity
In the previous example, `Fruit(2)` and `banana` refer to the same object, not just two objects that happen to be equal. You can verify using the `===` operator, which is the equivalent of Python's `is` operator:

In [ ]:
banana === Fruit(2)

You can also check this by looking at their `objectid()`, which is the equivalent of Python's `id()` function:

In [ ]:
objectid(banana)

In [ ]:
objectid(Fruit(2))

In [89]:
a = [1, 2, 4]
b = [1, 2, 4]
@assert a == b  # a and b are equal
@assert a !== b # but they are not the same object

In [ ]:
a === b